import tseslint from 'typescript-eslint';
import boundaries from 'eslint-plugin-boundaries';
import pluginVue from 'eslint-plugin-vue';
import vueTsEslintConfig from '@vue/eslint-config-typescript';

export default tseslint.config(
  { ignores: ['**/dist/**', '**/node_modules/**', '**/.vercel/**', '**/coverage/**'] },
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  ...vueTsEslintConfig(),
  {
    plugins: { boundaries },
    settings: {
      'boundaries/elements': [
        { type: 'domain', pattern: 'packages/domain/**' },
        { type: 'contracts', pattern: 'packages/contracts/**' },
        { type: 'ui', pattern: 'packages/ui/**' },
        { type: 'api', pattern: 'apps/api/**' },
        { type: 'web', pattern: 'apps/web/**' },
      ],
    },
    rules: {
      'boundaries/element-types': ['error', {
        default: 'disallow',
        rules: [
          { from: 'domain', allow: [] },
          { from: 'contracts', allow: ['domain'] },
          { from: 'ui', allow: [] },
          { from: 'api', allow: ['domain', 'contracts'] },
          { from: 'web', allow: ['domain', 'contracts', 'ui'] },
        ],
      }],
    },
  },
  {
    // Generated by the shadcn-vue CLI. Re-running `add` would revert any edit
    // made to satisfy these, so they are not enforced here.
    files: ['packages/ui/src/components/ui/**'],
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
      'vue/max-attributes-per-line': 'off',
    },
  },
);
