/**
 * Regenerates the currency catalogue: `catalogue.json` (what the tests check
 * and what a reviewer reads in the diff) and the migration that loads it.
 *
 * Run under Bun, from `apps/api`: `bun run catalogue:build`.
 *
 * Why the JSON is committed rather than derived at test time: names and scales
 * come from ICU, and the repo's two runtimes ship different CLDR vintages — the
 * rupiah has two decimals under one and none under the other. Deriving on the
 * fly would make the catalogue depend on which binary happened to run. One
 * generation, one committed artefact, one review.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCatalogue, type CatalogueRow } from './build.js';

const here = dirname(fileURLToPath(import.meta.url));
const MIGRATION = join(
  here,
  '../../../../supabase/migrations/20260920000014_currency_catalogue.sql',
);
const JSON_PATH = join(here, 'catalogue.json');

/** Single quotes doubled; everything here is ASCII-safe otherwise. */
const lit = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);

const row = (r: CatalogueRow) =>
  `  (${[
    lit(r.code),
    lit(r.kind),
    String(r.scale),
    lit(r.symbol),
    lit(r.nameRu),
    lit(r.nameEn),
    lit(r.rateSource),
    lit(r.coingeckoId),
  ].join(', ')})`;

function toSql(rows: CatalogueRow[]): string {
  const withoutSource = rows.filter((r) => r.rateSource === null).map((r) => r.code);
  return `-- Generated by apps/api/scripts/currency-catalogue/generate.ts. Do not hand-edit:
-- change the code lists in that directory and re-run \`bun run catalogue:build\`.
--
-- The full ISO 4217 catalogue plus the traded cryptocurrencies, and — per
-- ADR 0006 — where each one's rate comes from. \`rate_source is null\` means no
-- provider quotes it: the app says so and offers a manual rate, rather than
-- converting against a rate that is really a zero.

alter table public.currencies
  add column rate_source text check (rate_source in ('open-er-api', 'coingecko')),
  add column coingecko_id text unique;

comment on column public.currencies.rate_source is
  'Which provider quotes this currency. Null means none does; the rate can only be entered by hand.';
comment on column public.currencies.coingecko_id is
  'CoinGecko prices by its own id, not by ticker, so the id has to travel with the code.';

-- A fiat code cannot carry a CoinGecko id and a coin cannot be quoted by a
-- fiat provider, so the catalogue cannot drift into asking the wrong one.
alter table public.currencies add constraint currencies_source_matches_kind check (
  case kind
    when 'fiat' then coingecko_id is null and rate_source is distinct from 'coingecko'
    when 'crypto' then rate_source is distinct from 'open-er-api'
      and (rate_source is null) = (coingecko_id is null)
  end
);

-- The rates job walks the catalogue by source, so give it an index rather than
-- a sequential scan over a few hundred rows on every run.
create index currencies_rate_source_idx on public.currencies (rate_source)
  where rate_source is not null;

-- \`do update\` deliberately leaves kind, scale and symbol alone: the currencies
-- that shipped in the first catalogue already denominate people's balances, and
-- re-deciding a scale here would reinterpret stored money. Only the fields that
-- were empty — the names — and the new source columns are written.
insert into public.currencies (code, kind, scale, symbol, name_ru, name_en, rate_source, coingecko_id) values
${rows.map(row).join(',\n')}
on conflict (code) do update set
  name_ru = coalesce(public.currencies.name_ru, excluded.name_ru),
  name_en = coalesce(public.currencies.name_en, excluded.name_en),
  rate_source = excluded.rate_source,
  coingecko_id = excluded.coingecko_id;

-- ${rows.length} currencies: ${rows.filter((r) => r.kind === 'fiat').length} fiat, ${rows.filter((r) => r.kind === 'crypto').length} crypto.
-- Without a rate source (${withoutSource.length}): ${withoutSource.join(', ') || 'none'}.
`;
}

const rows = buildCatalogue();
writeFileSync(JSON_PATH, `${JSON.stringify(rows, null, 2)}\n`);
writeFileSync(MIGRATION, toSql(rows));
console.log(`${rows.length} currencies → catalogue.json and the migration`);
